#3.1 

In [1]:
import pandas as pd
import numpy as np
from sklearn.neural_network import MLPClassifier
from sklearn.model_selection import train_test_split
from sklearn.model_selection import cross_val_score
from sklearn import preprocessing
import matplotlib.pyplot as plt

In [4]:
with open("/content/misterious_data.txt") as f:
    content = f.readlines()

matrix = [[float(num) for num in x.split("\t")] for x in content]
y = np.array([row[0] for row in matrix])
x = np.array([row[1:] for row in matrix])

In [5]:
X_train, X_test, y_train, y_test = train_test_split(x, y, train_size=0.7 ,stratify=y)

In [6]:
clf = MLPClassifier(max_iter=300).fit(X_train, y_train)

In [7]:
print(cross_val_score(clf, X_test, y_test, cv=3))

[0.88461538 0.88461538 0.92307692]


#3.2

In [8]:
import seaborn as sns
diamonds = sns.load_dataset("diamonds")
diamonds.head()

carat      cut color clarity  depth  table  price     x     y     z
0   0.23    Ideal     E     SI2   61.5   55.0    326  3.95  3.98  2.43
1   0.21  Premium     E     SI1   59.8   61.0    326  3.89  3.84  2.31
2   0.23     Good     E     VS1   56.9   65.0    327  4.05  4.07  2.31
3   0.29  Premium     I     VS2   62.4   58.0    334  4.20  4.23  2.63
4   0.31     Good     J     SI2   63.3   58.0    335  4.34  4.35  2.75

In [9]:
y = pd.get_dummies(diamonds.cut)

In [10]:
color_coded = pd.get_dummies(diamonds.color)
clarity_coded = pd.get_dummies(diamonds.clarity)
diamonds = diamonds.drop(["cut","color","clarity"], axis=1)
diamonds = diamonds.join(color_coded)
diamonds = diamonds.join(clarity_coded)
X = diamonds

In [11]:
enc = preprocessing.OneHotEncoder()
enc.fit(y)
y = enc.transform(y).toarray()

In [12]:
X_train, X_test, y_train, y_test = train_test_split(X, y, train_size=0.7 ,stratify=y)

In [13]:
clf = MLPClassifier(max_iter=300).fit(X_train, y_train)

In [14]:
print(cross_val_score(clf, X_test, y_test, cv=3))

[0.06321839 0.03967371 0.02817946]


#3.3

In [30]:
from sklearn.datasets import load_boston
from sklearn.neural_network import MLPRegressor
from sklearn.preprocessing import StandardScaler

In [ ]:
X, y = load_boston(return_X_y=True)

In [33]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.7)

In [34]:
regr = MLPRegressor().fit(X_train, y_train)

/usr/local/lib/python3.7/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:696: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  ConvergenceWarning,


In [35]:
print(cross_val_score(regr, X_test, y_test, cv=3))

/usr/local/lib/python3.7/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:696: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  ConvergenceWarning,
/usr/local/lib/python3.7/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:696: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  ConvergenceWarning,


[0.52040766 0.53942955 0.67451323]


/usr/local/lib/python3.7/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:696: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  ConvergenceWarning,


In [36]:
regr.predict(X_test)
regr.score(X_test, y_test)

0.5348132133610524